import { useState } from "react";
import { ArrowRight, Car, Clock3, MapPin, Navigation, Search, Star, Wallet } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import RiderLayout from "../../layouts/RiderLayout";
import { recentRides, rideTypes, savedPlaces } from "../../data/riderMockData";

export default function RiderDashboard() {
  const { user } = useAuth(); const navigate = useNavigate();
  const [destination, setDestination] = useState(""); const [selected, setSelected] = useState("mini");
  return <RiderLayout activePage="Dashboard">
    <div className="mb-7"><p className="text-sm text-gray-500 dark:text-gray-400">Good evening 👋</p><h1 className="mt-1 text-3xl font-black">Where are you going, {user?.name?.split(" ")[0] || "Rider"}?</h1></div>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
      <section className="overflow-hidden rounded-3xl border border-gray-200 bg-white dark:border-[#2A2A2A] dark:bg-[#171717]">
        <div className="relative h-[330px] overflow-hidden bg-[#e8e5dc] dark:bg-[#1d1d1d]"><div className="absolute inset-0 opacity-50" style={{backgroundImage:"linear-gradient(25deg, transparent 48%, #b9b5aa 49%, #b9b5aa 51%, transparent 52%),linear-gradient(110deg, transparent 45%, #c8c4b9 46%, #c8c4b9 48%, transparent 49%)",backgroundSize:"130px 100px, 170px 130px"}}/><div className="absolute left-[34%] top-[42%] h-4 w-4 rounded-full border-4 border-[#F5C518] bg-black shadow-lg"/><div className="absolute right-[25%] top-[28%] h-4 w-4 rounded-full bg-black shadow-lg"/><div className="absolute left-[36%] top-[43%] h-1 w-[40%] rotate-[-18deg] bg-[#F5C518]"/><div className="absolute left-5 top-5 rounded-xl bg-white/90 px-3 py-2 text-xs font-semibold shadow dark:bg-[#111]/90">Live service area</div></div>
        <div className="p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">Where to?</h2><p className="text-sm text-gray-500 dark:text-gray-400">Choose your pickup and destination</p></div><Navigation size={20}/></div>
          <div className="space-y-3"><div className="flex items-center gap-3 rounded-xl bg-gray-50 p-3 dark:bg-[#1f1f1f]"><MapPin size={18} className="text-[#C9A000]"/><input className="w-full bg-transparent outline-none" value="Current location" readOnly/></div><div className="flex items-center gap-3 rounded-xl border border-gray-200 p-3 dark:border-[#333]"><Search size={18}/><input className="w-full bg-transparent outline-none" placeholder="Where are you going?" value={destination} onChange={e=>setDestination(e.target.value)}/></div></div>
          {destination && <div className="mt-4 grid grid-cols-3 gap-2">{rideTypes.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`rounded-xl border p-3 text-left ${selected===r.id?"border-[#F5C518] bg-[#FFF9E5] dark:bg-[#2A2410]":"border-gray-200 dark:border-[#333]"}`}><p className="font-bold">{r.label}</p><p className="text-xs text-gray-500">{r.eta} · ₹{r.fare}</p></button>)}</div>}
          <button onClick={()=>navigate("/rider/book",{state:{destination,selected}})} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#F5C518] px-5 py-3 font-bold text-black hover:bg-[#E5B600]">Book a ride <ArrowRight size={18}/></button>
        </div>
      </section>
      <div className="space-y-6"><section className="rounded-3xl border border-gray-200 bg-white p-6 dark:border-[#2A2A2A] dark:bg-[#171717]"><div className="flex items-center justify-between"><h2 className="font-bold">Saved places</h2><button className="text-sm font-semibold text-[#9B7A00]">Manage</button></div>{savedPlaces.map(p=><div key={p.label} className="mt-4 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F5C518]/20"><MapPin size={18}/></div><div><p className="font-semibold">{p.label}</p><p className="text-xs text-gray-500 dark:text-gray-400">{p.address}</p></div></div>)}</section><section className="rounded-3xl bg-[#0B0B0B] p-6 text-white"><p className="text-sm text-gray-400">CABX OFFER</p><h2 className="mt-2 text-2xl font-black">20% OFF</h2><p className="mt-1 text-sm text-gray-300">Your next ride. Use code <b className="text-[#F5C518]">CABX20</b></p><button className="mt-4 rounded-xl bg-[#F5C518] px-4 py-2 text-sm font-bold text-black">View offer</button></section></div>
    </div>
    <section className="mt-6 rounded-3xl border border-gray-200 bg-white p-6 dark:border-[#2A2A2A] dark:bg-[#171717]"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">Recent rides</h2><p className="text-sm text-gray-500 dark:text-gray-400">Your latest CabX trips</p></div><button onClick={()=>navigate("/rider/history")} className="text-sm font-bold">View all →</button></div><div className="grid gap-3 lg:grid-cols-2">{recentRides.slice(0,2).map(r=><div key={r.id} className="flex items-center justify-between rounded-2xl bg-gray-50 p-4 dark:bg-[#1e1e1e]"><div><p className="font-semibold">{r.route}</p><p className="mt-1 text-xs text-gray-500">{r.date} · {r.status}</p></div><div className="text-right"><p className="font-bold">₹{r.fare}</p><p className="text-xs text-gray-500">{r.payment}</p></div></div>)}</div></section>
  </RiderLayout>;
}
